name: Testing
on: [push]
jobs:
  test-fakernet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and run tests
        run: |
          ./scripts/github/install_github_ubuntu.sh
          sudo --user fakernet ./scripts/github/run_github_build.sh
          echo "DNS=172.16.3.2#test 8.8.8.8" | sudo tee --append /etc/systemd/resolved.conf
          echo "FallbackDNS=1.1.1.1" | sudo tee --append /etc/systemd/resolved.conf
          echo "Domains=~test" | sudo tee --append /etc/systemd/resolved.conf
          sudo service systemd-resolved restart
          sudo systemd-resolve --status
          sudo --user fakernet ./scripts/github/run_github_tests.sh
      - name: Upload any testlogs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: testlogs
          path: |
            ./testlogs/*